---
# tasks file for kurtabersold.letsencrypt
- name: Install git
  apt: name=git update_cache=yes

- name: Clone Certbot repo
  git: repo=https://github.com/certbot/certbot.git
       dest=/opt/letsencrypt
       version=master
       update=yes
       accept_hostkey=yes

- name: Create Letsencrypt Config Directory
  file: path=/etc/letsencrypt owner=root group=root mode=0755 state=directory

- name: Letsencrypt Config Template
  template: src=templates/standalone-cli.ini dest=/etc/letsencrypt/cli.ini force=yes owner=root group=root mode=0640

- name: Run certbot-auto certonly (Standalone server on port 443)
  shell: /opt/letsencrypt/certbot-auto --non-interactive certonly
  args:
    chdir: /opt/letsencrypt
    creates: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem

- name: Certificate Renewal Subscripts Directory
  file: path=/usr/local/bin/renew/renew.d owner=root group=root mode=0755 state=directory

- name: Certificate Renewal Script
  copy: src=files/renew.sh dest=/usr/local/bin/renew/renew.sh owner=root group=root mode=0774 force=yes

- name: Letsencrypt Standalone Config Template
  template: src=templates/standalone-cli.ini dest=/etc/letsencrypt/cli.ini force=yes owner=root group=root mode=0640

- name: Systemd unit files
  template:
    src: "{{ item.src }}"
    dest: /etc/systemd/system/{{ item.dest }}
    owner: root
    group: root
    mode: 0755
    force: yes
  with_items:
    - { src: 'templates/certbot.service', dest: 'certbot.service' }
    - { src: 'templates/certbot.timer', dest: 'certbot.timer' }
  notify:
    - enable certbot
