---
# tasks file for letsencrypt

- include: tags_processing.yml

- include: install.yml 
  tags: letsencrypt, letsencrypt:install
  when: (letsencrypt_install.skipped is undefined) or
        (letsencrypt_defaults.skipped is undefined)

- include: uninstall.yml
  tags: letsencrypt:uninstall
  when: letsencrypt_uninstall.skipped is undefined

# If you use the same role, many times in your playbook its important
# to reset those values to their default
- name: Reseting letsencrypt Arguments
  set_fact:
    letsencrypt_install: false
    letsencrypt_uninstall: false
    letsencrypt_start: false
  tags: always

